/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class diqiuzhuanzhuan_App */

#ifndef _Included_diqiuzhuanzhuan_App
#define _Included_diqiuzhuanzhuan_App
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     diqiuzhuanzhuan_App
 * Method:    intMethod
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_diqiuzhuanzhuan_App_intMethod
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
